# Vim Variables
runtime cfgsrc/vimsettings.vim

# key mappings
runtime cfgsrc/mykeybinds.vim

# Plugins
runtime cfgsrc/plugins.vim

# VIM-LSP
runtime cfgsrc/lsp-cfg.vim
#let g:lsp_log_verbose = 1
#let g:lsp_log_file = expand('~/.vim/log/vim-lsp.log')

# Vimspector
let g:vimspector_base_dir=expand( '$HOME/.vim/vimspector-configs' )
let g:vimspector_enable_mappings='HUMAN'

# Vista - tagbar replacement
#let g:vista#renderer#ctags = 'kind'
let g:vista#renderer#enable_icon = 1
let g:vista_icon_indent = ["╰─▸ ", "├─▸ "]

# tokyonight configurations
let g:tokyonight_style = 'night'
let g:tokyonight_enable_italic = 1

# sonokai configurations
let g:sonokai_style = 'default'
let g:sonokai_enable_italic = 1
let g:sonokai_disable_italic_comment = 1

# colorscheme selection
#set background=dark
colorscheme sonokai


